spring:
  application:
    name: config-server-3344
    
    
---
spring:
  application:
    name: config-server-3344-dev
  profiles:
    active: dev   
---
spring:
  application:
    name: config-server-3344-tt
  profiles:
    active: tt    
---
spring:
  application:
    name: config-server-3344-master
  profiles:
    active: master
