config-provider-server: config-provider-server-8001

spring:
  profiles:
    active: dev
    
---
server:
  port: 8001


spring:
  profiles:
    active: pro
  application:
    name: config-provider-service-pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lhytest?useUnicode=true&characterEncoding=UTF-8


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.gcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka


---
server:
  port: 8001


spring:
  profiles:
    active: dev
  application:
    name: config-provider-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lhytest?useUnicode=true&characterEncoding=UTF-8


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.gcloud.entity
  mapper-locations: classpath:mybatis/mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka
